<?php

define("NS_PRINTABLEWERELATE_PERSON", 500);
define("NS_PRINTABLEWERELATE_PERSON_TALK", 501);
$wgExtraNamespaces[NS_PRINTABLEWERELATE_PERSON] = "Person";
$wgExtraNamespaces[NS_PRINTABLEWERELATE_PERSON_TALK] = "Person_talk";
$wgContentNamespaces[] = NS_PRINTABLEWERELATE_PERSON;

define("NS_PRINTABLEWERELATE_FAMILY", 502);
define("NS_PRINTABLEWERELATE_FAMILY_TALK", 503);
$wgExtraNamespaces[NS_PRINTABLEWERELATE_FAMILY] = "Family";
$wgExtraNamespaces[NS_PRINTABLEWERELATE_FAMILY_TALK] = "Family_talk";
$wgContentNamespaces[] = NS_PRINTABLEWERELATE_FAMILY;
